name: Docker Base Image

on:
  push:
    branches: ["main"]
    paths:
      - 'docker/Dockerfile'
      - 'scripts/ubuntu-build/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-base:
    runs-on: ubuntu-24.04-32

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache `base` stage
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          ulimit: "memlock=-1:-1"
          target: base
          cache-from: type=gha,scope=base
          cache-to: type=gha,scope=base,mode=max
