name: License

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'third_party/**'
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
    paths-ignore:
      - 'third_party/**'

permissions:
  contents: read

jobs:
  check-license:
    runs-on: ubuntu-24.04-32

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check licenses
        run: .github/workflows/license.sh
